---
title: "p8105_hw6_tj2519"
output: github_document
date: "2023-11-29"
---

```{r}
library(tidyverse)
library(p8105.datasets)
```

# Problem 2
## Initial setup (load the dataset) and create a bootstrap function
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())

boot_sample = function(df) {
  sample_frac(df, replace = TRUE)
}

bootboot_straps = 
  tibble(strap_number = 1:500) |> 
  mutate(
    strap_sample = map(strap_number, \(df) boot_sample(weather_df))
  )

```


## Run Linear Regression to the samples and calculate the log(b1*b2) and r^2 for each bootstrap sample
```{r}
bootboot_straps_results =
  bootboot_straps %>% 
  mutate(
    models = map(strap_sample, \(df) lm(tmax ~ tmin + prcp, data = df)),
    results = map(models, broom::tidy),
    r_sq = map(models, broom::glance),
    log_value = map_dbl(results, ~log(.x[[2]][[2]] * .x[[2]][[3]]))) %>% 
  mutate(r_sq = map(r_sq, ~ .x %>% select(r.squared))) %>% 
  select(-strap_sample, -models) %>% 
  unnest(results, r_sq) %>% 
  janitor::clean_names()


  
```

## Plot the estimate distributions (r^2 and log(beta1*beta2))
```{r}
bootboot_straps_results %>% 
  ggplot(aes(x = r_squared)) + 
  geom_density() +
  labs(title = "Distribution of r_squared Across the Samples")


bootboot_straps_results %>% 
  ggplot(aes(x = log_value)) + 
  geom_density() +
  labs(title = "Distribution of log(beta1*beta2) Across the Samples")
  
```



```{r}



  mutate(ci_lower = map_dbl(estimate, quantile(0.025)),
         ci_upper = map_dbl(estimate, quantile(0.975))) 
```

